import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import CalculatorEngine from "@/components/calculators/CalculatorEngine";
import SisterSiteCard from "@/components/layout/SisterSiteCard";
import { calculators, getCalculator, getRelatedCalculators } from "@/lib/calculators/data";
import { getProgrammaticHubLinks } from "@/lib/calculators/programmatic";
import { calculatorKeywordLine, localizeCalculatorDefinition, localizeCalculatorName, localizeCategoryName, localizeDescription, localizeProgrammaticExample } from "@/lib/calculators/localization";
import { calculatorSlugToSisterTopic } from "@/lib/seo/sister-sites";
import { normalizeLocale, withLocale } from "@/lib/i18n";

const SITE_URL = "https://mega-calculators.com";
export function generateStaticParams() { return calculators.flatMap((calculator) => [{ locale: "en", category: calculator.category, slug: calculator.slug }, { locale: "ko", category: calculator.category, slug: calculator.slug }]); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; category: string; slug: string }> }): Promise<Metadata> {
  const { locale: rawLocale, category, slug } = await params; const locale = normalizeLocale(rawLocale); const calculator = getCalculator(category, slug); if (!calculator) return {}; const localized = localizeCalculatorDefinition(calculator, locale); const canonical = `${SITE_URL}/${locale}/calculators/${calculator.category}/${calculator.slug}`;
  return { title: locale === "ko" ? `${localized.name} | Mega Calculators` : `${calculator.name} - Free Online Calculator`, description: localizeDescription(calculator, locale), keywords: locale === "ko" ? [localized.name, calculatorKeywordLine(calculator, locale), `${localized.name} 사용법`, `${localized.name} 계산`] : [calculator.name, `${calculator.name} online`, `${calculator.name} free`, calculator.categoryName.toLowerCase()], alternates: { canonical, languages: { en: `${SITE_URL}/en/calculators/${calculator.category}/${calculator.slug}`, ko: `${SITE_URL}/ko/calculators/${calculator.category}/${calculator.slug}`, "x-default": `${SITE_URL}/en/calculators/${calculator.category}/${calculator.slug}` } }, openGraph: { title: locale === "ko" ? `${localized.name} | Mega Calculators` : `${calculator.name} - Mega Calculators`, description: localizeDescription(calculator, locale), url: canonical, siteName: "Mega Calculators", locale: locale === "ko" ? "ko_KR" : "en_US", alternateLocale: locale === "ko" ? ["en_US"] : ["ko_KR"], type: "website", images: [{ url: `/opengraph-image?locale=${locale}`, width: 1200, height: 630 }] }, twitter: { card: "summary_large_image", title: localized.name, description: localizeDescription(calculator, locale), images: [`/opengraph-image?locale=${locale}`] } };
}
export default async function CalculatorPage({ params, searchParams }: { params: Promise<{ locale: string; category: string; slug: string }>; searchParams?: Promise<{ embed?: string }> }) {
  const { locale: rawLocale, category, slug } = await params; const query = searchParams ? await searchParams : {}; const embedMode = query.embed === "1"; const locale = normalizeLocale(rawLocale); const calculator = getCalculator(category, slug); if (!calculator) notFound(); const localized = localizeCalculatorDefinition(calculator, locale);
  const related = getRelatedCalculators(calculator.relatedSlugs).map((item) => ({ name: localizeCalculatorName(item.name, locale, item.slug), href: withLocale(locale, `/calculators/${item.category}/${item.slug}`) }));
  const links = getProgrammaticHubLinks(calculator); const hubLinks = { formula: withLocale(locale, links.formula), guide: withLocale(locale, links.guide), useCases: withLocale(locale, links.useCases), examples: links.examples.map((item) => ({ title: localizeProgrammaticExample({ slug: "", title: item.title, description: "", intro: "", overrides: {} }, calculator, locale).title, href: withLocale(locale, item.href) })) };
  const url = `${SITE_URL}/${locale}/calculators/${calculator.category}/${calculator.slug}`;
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: localized.faq.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) };
  const appSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: localized.name, applicationCategory: "UtilitiesApplication", operatingSystem: "Web", description: localized.description, offers: { "@type": "Offer", price: "0", priceCurrency: locale === "ko" ? "KRW" : "USD" }, url, inLanguage: locale === "ko" ? "ko-KR" : "en-US" };
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: locale === "ko" ? "홈" : "Home", item: `${SITE_URL}/${locale}` }, { "@type": "ListItem", position: 2, name: locale === "ko" ? "계산기" : "Calculators", item: `${SITE_URL}/${locale}/calculators` }, { "@type": "ListItem", position: 3, name: localizeCategoryName(calculator.category, locale), item: `${SITE_URL}/${locale}/calculators/${calculator.category}` }, { "@type": "ListItem", position: 4, name: localized.name, item: url }] };
  return <div className={embedMode ? "bg-white" : "space-y-8"}>{embedMode ? <style>{`header, footer { display: none !important; } main { max-width: none !important; padding: 0 !important; min-height: 100vh !important; } body { background: white; }`}</style> : null}{!embedMode ? <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(appSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} /><nav className="text-sm text-slate-500"><Link href={withLocale(locale, "/")}>{locale === "ko" ? "홈" : "Home"}</Link><span className="mx-2">/</span><Link href={withLocale(locale, "/calculators")}>{locale === "ko" ? "계산기" : "Calculators"}</Link><span className="mx-2">/</span><Link href={withLocale(locale, `/calculators/${calculator.category}`)}>{localizeCategoryName(calculator.category, locale)}</Link></nav></> : null}<CalculatorEngine definition={localized} relatedLinks={related} hubLinks={hubLinks} locale={locale} embedMode={embedMode} />{!embedMode ? (() => { const topic = calculatorSlugToSisterTopic(calculator.slug); return topic ? <SisterSiteCard topic={topic} locale={locale} /> : null; })() : null}</div>;
}
