import type { NextConfig } from "next";

const legacyCalculatorRedirects = [
  { oldCategory: "finance", newCategory: "business", slug: "annual-income-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "biweekly-paycheck-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "business-loan-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "debt-to-income-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "dividend-income-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "hourly-wage-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "net-pay-raise-calculator" },
  { oldCategory: "finance", newCategory: "business", slug: "paycheck-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "bmr-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "calorie-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "calorie-deficit-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "daily-protein-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "lean-bulk-calorie-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "one-rep-max-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "pace-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "pace-per-km-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "pace-per-mile-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "protein-intake-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "protein-per-meal-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "running-calories-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "target-body-fat-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "target-heart-rate-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "tdee-calculator" },
  { oldCategory: "health", newCategory: "fitness", slug: "walking-calories-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "break-even-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "commission-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "freelance-rate-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "hourly-to-salary-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "markdown-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "markup-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "overtime-pay-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "salary-to-hourly-calculator" },
  { oldCategory: "life", newCategory: "business", slug: "sales-tax-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "concrete-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "fence-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "flooring-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "mulch-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "paint-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "pool-volume-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "tile-calculator" },
  { oldCategory: "life", newCategory: "construction", slug: "wallpaper-calculator" },
  { oldCategory: "life", newCategory: "education", slug: "gpa-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "appliance-energy-cost-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "babysitting-cost-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "cat-age-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "discount-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "dog-age-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "fuel-cost-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "moving-cost-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "rent-split-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "road-trip-cost-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "sleep-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "split-bill-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "tip-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "travel-budget-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "unit-price-calculator" },
  { oldCategory: "life", newCategory: "everyday-life", slug: "utility-bill-split-calculator" },
  { oldCategory: "life", newCategory: "finance", slug: "rule-of-72-calculator" },
  { oldCategory: "life", newCategory: "food-cooking", slug: "meal-prep-cost-calculator" },
  { oldCategory: "life", newCategory: "food-cooking", slug: "party-budget-calculator" },
  { oldCategory: "math", newCategory: "physics-science", slug: "density-calculator" },
  { oldCategory: "math", newCategory: "statistics", slug: "average-calculator" },
  { oldCategory: "math", newCategory: "statistics", slug: "probability-calculator" },
  { oldCategory: "math", newCategory: "statistics", slug: "standard-deviation-calculator" },
  { oldCategory: "math", newCategory: "statistics", slug: "weighted-average-calculator" },
  { oldCategory: "time", newCategory: "education", slug: "study-hours-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "age-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "business-days-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "commute-time-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "countdown-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "date-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "date-difference-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "days-between-dates-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "days-to-hours-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "deadline-days-left-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "hours-between-times-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "hours-to-minutes-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "meeting-duration-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "minutes-to-seconds-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "months-to-days-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "overtime-hours-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "pay-period-hours-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "project-hours-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "pto-accrual-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "shift-break-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "time-duration-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "week-number-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "weeks-to-days-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "work-hours-calculator" },
  { oldCategory: "time", newCategory: "time-date", slug: "years-to-months-calculator" },
  { oldCategory: "unit-converters", newCategory: "computer-tech", slug: "data-storage-converter" },
  { oldCategory: "unit-converters", newCategory: "computer-tech", slug: "digital-storage-converter" },
  { oldCategory: "unit-converters", newCategory: "construction", slug: "land-area-converter" },
  { oldCategory: "unit-converters", newCategory: "food-cooking", slug: "cooking-volume-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "air-pressure-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "angle-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "battery-charge-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "density-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "electric-charge-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "electricity-power-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "energy-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "flow-rate-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "force-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "frequency-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "geometry-angle-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "heat-energy-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "load-force-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "magnetic-field-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "material-density-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "power-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "pressure-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "rotational-torque-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "signal-frequency-converter" },
  { oldCategory: "unit-converters", newCategory: "physics-science", slug: "torque-converter" },
  { oldCategory: "unit-converters", newCategory: "time-date", slug: "duration-unit-converter" },
  { oldCategory: "unit-converters", newCategory: "time-date", slug: "time-unit-converter" },
] as const;

const nextConfig: NextConfig = {
  async redirects() {
    const calculatorRedirects = legacyCalculatorRedirects.flatMap((item) => [
      { source: `/calculators/${item.oldCategory}/${item.slug}`, destination: `/calculators/${item.newCategory}/${item.slug}`, permanent: true },
      { source: `/:locale/calculators/${item.oldCategory}/${item.slug}`, destination: `/:locale/calculators/${item.newCategory}/${item.slug}`, permanent: true },
    ]);

    return [
      { source: "/cal", destination: "/en/calculators", permanent: true },
      { source: "/cal/calculator", destination: "/en/calculators", permanent: true },
      { source: "/cal/cal/calculator", destination: "/en/calculators", permanent: true },
      { source: "/cal/fire", destination: "/en/calculators/finance/retirement-calculator", permanent: true },
      { source: "/cal/cal/fire", destination: "/en/calculators/finance/retirement-calculator", permanent: true },
      { source: "/cal/capital-gains", destination: "/en/calculators/finance/capital-gains-tax-calculator", permanent: true },
      { source: "/cal/cal/capital-gains", destination: "/en/calculators/finance/capital-gains-tax-calculator", permanent: true },
      { source: "/cal/retirement-tax", destination: "/en/calculators/finance/retirement-calculator", permanent: true },
      { source: "/cal/cal/retirement-tax", destination: "/en/calculators/finance/retirement-calculator", permanent: true },
      { source: "/calculators/time", destination: "/calculators/time-date", permanent: true },
      { source: "/:locale/calculators/time", destination: "/:locale/calculators/time-date", permanent: true },
      { source: "/calculators/life", destination: "/calculators/everyday-life", permanent: true },
      { source: "/:locale/calculators/life", destination: "/:locale/calculators/everyday-life", permanent: true },
      ...calculatorRedirects,
    ];
  },
};

export default nextConfig;
