import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { calculatorCategories, calculators, calculatorsByCategory, getCalculator, getRelatedCalculators } from "@/lib/calculators/data";
import { normalizeLocale, withLocale } from "@/lib/i18n";
import { calculatorKeywordLine, localizeCalculatorDefinition, localizeCalculatorName, localizeCategoryName, localizeDescription, localizeUiText } from "@/lib/calculators/localization";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const locale = normalizeLocale((await params).locale); return { title: locale === "ko" ? "전체 계산기" : "All Calculators", description: locale === "ko" ? `금융, 비즈니스, 건강, 피트니스, 수학, 통계, 단위 변환, 시간·날짜, 건축, 요리, 기술, 과학, 교육, 생활 분야의 계산기 ${calculators.length}개를 한 번에 둘러볼 수 있습니다.` : `Browse ${calculators.length} free online calculators and converters across finance, business, health, fitness, math, statistics, unit conversion, time and date, construction, cooking, technology, science, education, and everyday life topics.`, alternates: { canonical: `/${locale}/calculators`, languages: { en: "/en/calculators", ko: "/ko/calculators" } } }; }
export default async function AllCalculatorsPage({ params }: { params: Promise<{ locale: string }> }) { const locale = normalizeLocale((await params).locale); const isKo = locale === "ko"; const categorySections = calculatorCategories.map((category) => ({ ...category, localizedName: localizeCategoryName(category.slug, locale), items: calculators.filter((item) => item.category === category.slug).map((item) => localizeCalculatorDefinition(item, locale)) })); return <div className="space-y-8"><section><div className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-700">{isKo ? "전체 계산기" : "All calculators"}</div><h1 className="mt-2 text-4xl font-black tracking-tight text-slate-950">{isKo ? `무료 온라인 계산기 ${calculators.length}개 둘러보기` : `Browse all ${calculators.length} free online calculators`}</h1><p className="mt-4 max-w-3xl text-base leading-8 text-slate-600">{isKo ? "세분화된 카테고리별로 계산기를 빠르게 찾아보고, 필요한 페이지에서 바로 계산할 수 있습니다." : "Explore calculators by category to quickly find finance, business, health, fitness, math, statistics, unit converters, time and date, construction, cooking, tech, science, education, and everyday life tools."}</p></section>{categorySections.map((category) => <section key={category.slug} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-slate-950">{category.localizedName}</h2><p className="mt-2 text-sm text-slate-600">{category.items.length} {isKo ? "개 계산기" : "calculators in this category."}</p></div><Link href={withLocale(locale, `/calculators/${category.slug}`)} className="text-sm font-semibold text-blue-700">{isKo ? "카테고리 페이지 →" : "Category page →"}</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{category.items.map((item) => <Link key={`${item.category}-${item.slug}`} href={withLocale(locale, `/calculators/${item.category}/${item.slug}`)} className="rounded-2xl border border-slate-200 p-4 transition hover:border-blue-300 hover:bg-blue-50"><div className="text-base font-semibold text-slate-900">{item.name}</div><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></Link>)}</div></section>)}</div>; }
