import type { CalculatorDefinition } from "@/lib/calculators/data";

export const calculatorCategories = [
  { slug: "finance", name: "Finance Calculators" },
  { slug: "business", name: "Business Calculators" },
  { slug: "health", name: "Health Calculators" },
  { slug: "fitness", name: "Fitness Calculators" },
  { slug: "math", name: "Math Calculators" },
  { slug: "statistics", name: "Statistics Calculators" },
  { slug: "unit-converters", name: "Unit Converters" },
  { slug: "time-date", name: "Time & Date Calculators" },
  { slug: "construction", name: "Construction Calculators" },
  { slug: "food-cooking", name: "Food & Cooking Calculators" },
  { slug: "computer-tech", name: "Computer & Tech Calculators" },
  { slug: "physics-science", name: "Physics & Science Calculators" },
  { slug: "education", name: "Education Calculators" },
  { slug: "everyday-life", name: "Everyday Life Calculators" },
  { slug: "other", name: "Other Calculators" },
] as const;

export type CalculatorCategorySlug = (typeof calculatorCategories)[number]["slug"];

export const categoryNameBySlug: Record<CalculatorCategorySlug, string> = Object.fromEntries(calculatorCategories.map((category) => [category.slug, category.name])) as Record<CalculatorCategorySlug, string>;

const calculatorCategoryBySlug: Record<string, CalculatorCategorySlug> = {
  "age-calculator": "time-date",
  "air-pressure-converter": "physics-science",
  "amortization-calculator": "finance",
  "angle-converter": "physics-science",
  "annual-income-calculator": "business",
  "appliance-energy-cost-calculator": "everyday-life",
  "apr-calculator": "finance",
  "area-converter": "unit-converters",
  "auto-loan-calculator": "finance",
  "average-calculator": "statistics",
  "babysitting-cost-calculator": "everyday-life",
  "battery-charge-converter": "physics-science",
  "biweekly-paycheck-calculator": "business",
  "bmi-calculator": "health",
  "bmi-prime-calculator": "health",
  "bmr-calculator": "fitness",
  "body-fat-calculator": "health",
  "body-surface-area-calculator": "health",
  "break-even-calculator": "business",
  "budget-calculator": "finance",
  "business-days-calculator": "time-date",
  "business-loan-calculator": "business",
  "calorie-calculator": "fitness",
  "calorie-deficit-calculator": "fitness",
  "capital-gains-tax-calculator": "finance",
  "car-affordability-calculator": "finance",
  "cat-age-calculator": "everyday-life",
  "circle-area-calculator": "math",
  "circle-circumference-calculator": "math",
  "college-savings-calculator": "finance",
  "commission-calculator": "business",
  "commute-time-calculator": "time-date",
  "compound-interest-calculator": "finance",
  "concrete-calculator": "construction",
  "cooking-volume-converter": "food-cooking",
  "countdown-calculator": "time-date",
  "credit-card-payoff-calculator": "finance",
  "cube-root-calculator": "math",
  "daily-protein-calculator": "fitness",
  "data-storage-converter": "computer-tech",
  "date-calculator": "time-date",
  "date-difference-calculator": "time-date",
  "days-between-dates-calculator": "time-date",
  "days-to-hours-calculator": "time-date",
  "deadline-days-left-calculator": "time-date",
  "debt-payoff-calculator": "finance",
  "debt-to-income-calculator": "business",
  "decimal-to-percent-calculator": "math",
  "density-calculator": "physics-science",
  "density-converter": "physics-science",
  "digital-storage-converter": "computer-tech",
  "discount-calculator": "everyday-life",
  "distance-formula-calculator": "math",
  "dividend-income-calculator": "business",
  "dividend-yield-calculator": "finance",
  "dog-age-calculator": "everyday-life",
  "down-payment-savings-calculator": "finance",
  "dubois-body-surface-area-calculator": "health",
  "duration-unit-converter": "time-date",
  "electric-charge-converter": "physics-science",
  "electricity-power-converter": "physics-science",
  "emergency-fund-calculator": "finance",
  "energy-converter": "physics-science",
  "exponent-calculator": "math",
  "factorial-calculator": "math",
  "fence-calculator": "construction",
  "flooring-calculator": "construction",
  "flow-rate-converter": "physics-science",
  "force-converter": "physics-science",
  "fraction-calculator": "math",
  "freelance-rate-calculator": "business",
  "frequency-converter": "physics-science",
  "fuel-cost-calculator": "everyday-life",
  "fuel-economy-converter": "unit-converters",
  "fuel-volume-converter": "unit-converters",
  "future-value-calculator": "finance",
  "gcd-calculator": "math",
  "geometry-angle-converter": "physics-science",
  "gpa-calculator": "education",
  "heart-rate-calculator": "health",
  "heat-energy-converter": "physics-science",
  "hourly-to-salary-calculator": "business",
  "hourly-wage-calculator": "business",
  "hours-between-times-calculator": "time-date",
  "hours-to-minutes-calculator": "time-date",
  "house-down-payment-calculator": "finance",
  "hydration-calculator": "health",
  "ideal-weight-calculator": "health",
  "inflation-calculator": "finance",
  "interest-rate-calculator": "finance",
  "investment-calculator": "finance",
  "ira-calculator": "finance",
  "land-area-converter": "construction",
  "lcm-calculator": "math",
  "lean-body-mass-calculator": "health",
  "lean-bulk-calorie-calculator": "fitness",
  "lease-vs-buy-calculator": "finance",
  "length-converter": "unit-converters",
  "liquid-volume-converter": "unit-converters",
  "load-force-converter": "physics-science",
  "loan-calculator": "finance",
  "log-calculator": "math",
  "magnetic-field-converter": "physics-science",
  "markdown-calculator": "business",
  "markup-calculator": "business",
  "material-density-converter": "physics-science",
  "meal-prep-cost-calculator": "food-cooking",
  "meeting-duration-calculator": "time-date",
  "minutes-to-seconds-calculator": "time-date",
  "months-to-days-calculator": "time-date",
  "mortgage-calculator": "finance",
  "moving-cost-calculator": "everyday-life",
  "mulch-calculator": "construction",
  "net-pay-raise-calculator": "business",
  "net-worth-calculator": "finance",
  "one-rep-max-calculator": "fitness",
  "overtime-hours-calculator": "time-date",
  "overtime-pay-calculator": "business",
  "ovulation-calculator": "health",
  "pace-calculator": "fitness",
  "pace-per-km-calculator": "fitness",
  "pace-per-mile-calculator": "fitness",
  "paint-calculator": "construction",
  "party-budget-calculator": "food-cooking",
  "pay-period-hours-calculator": "time-date",
  "paycheck-calculator": "business",
  "percent-change-calculator": "math",
  "percent-to-decimal-calculator": "math",
  "percentage-calculator": "math",
  "percentage-decrease-calculator": "math",
  "percentage-increase-calculator": "math",
  "percentage-of-total-calculator": "math",
  "personal-loan-calculator": "finance",
  "pool-volume-calculator": "construction",
  "power-converter": "physics-science",
  "power-function-calculator": "math",
  "pregnancy-due-date-calculator": "health",
  "present-value-calculator": "finance",
  "pressure-converter": "physics-science",
  "probability-calculator": "statistics",
  "project-hours-calculator": "time-date",
  "protein-intake-calculator": "fitness",
  "protein-per-meal-calculator": "fitness",
  "pto-accrual-calculator": "time-date",
  "pythagorean-theorem-calculator": "math",
  "ratio-calculator": "math",
  "ratio-to-percentage-calculator": "math",
  "real-return-calculator": "finance",
  "rectangle-area-calculator": "math",
  "refinance-savings-calculator": "finance",
  "rent-split-calculator": "everyday-life",
  "rent-vs-buy-calculator": "finance",
  "retirement-calculator": "finance",
  "road-trip-cost-calculator": "everyday-life",
  "roi-calculator": "finance",
  "rotational-torque-converter": "physics-science",
  "rule-of-72-calculator": "finance",
  "running-calories-calculator": "fitness",
  "salary-to-hourly-calculator": "business",
  "sales-tax-calculator": "business",
  "savings-calculator": "finance",
  "savings-goal-calculator": "finance",
  "savings-rate-calculator": "finance",
  "shift-break-calculator": "time-date",
  "signal-frequency-converter": "physics-science",
  "simple-interest-calculator": "finance",
  "sleep-calculator": "everyday-life",
  "slope-calculator": "math",
  "speed-converter": "unit-converters",
  "split-bill-calculator": "everyday-life",
  "square-root-calculator": "math",
  "standard-deviation-calculator": "statistics",
  "stock-average-calculator": "finance",
  "student-loan-calculator": "finance",
  "study-hours-calculator": "education",
  "target-body-fat-calculator": "fitness",
  "target-heart-rate-calculator": "fitness",
  "tdee-calculator": "fitness",
  "temperature-converter": "unit-converters",
  "tile-calculator": "construction",
  "time-duration-calculator": "time-date",
  "time-unit-converter": "time-date",
  "tip-calculator": "everyday-life",
  "torque-converter": "physics-science",
  "travel-budget-calculator": "everyday-life",
  "triangle-area-calculator": "math",
  "unit-price-calculator": "everyday-life",
  "utility-bill-split-calculator": "everyday-life",
  "volume-converter": "unit-converters",
  "waist-to-height-ratio-calculator": "health",
  "waist-to-hip-ratio-calculator": "health",
  "walking-calories-calculator": "fitness",
  "wallpaper-calculator": "construction",
  "water-intake-calculator": "health",
  "week-number-calculator": "time-date",
  "weeks-to-days-calculator": "time-date",
  "weight-converter": "unit-converters",
  "weighted-average-calculator": "statistics",
  "work-hours-calculator": "time-date",
  "years-to-months-calculator": "time-date",
};

export function getCanonicalCategorySlug(slug: string, fallback: string): CalculatorCategorySlug {
  const mapped = calculatorCategoryBySlug[slug];
  if (mapped) return mapped;
  return calculatorCategories.some((category) => category.slug === fallback) ? (fallback as CalculatorCategorySlug) : "other";
}

export function applyCanonicalCalculatorCategory(calculator: CalculatorDefinition): CalculatorDefinition {
  const category = getCanonicalCategorySlug(calculator.slug, calculator.category);
  return { ...calculator, category, categoryName: categoryNameBySlug[category] };
}

export function getCategoryName(category: string) {
  return categoryNameBySlug[category as CalculatorCategorySlug] ?? categoryNameBySlug.other;
}
